spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your-db-name
    username: your-username
    password:  your-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
      host: smtp.gmail.com
      port: 587
      username: your-username
      password: your-password
      properties:
        mail:
          smtp:
            connection-timeout: 8000
            timeout: 8000
            write-timeout: 8000
            auth: true
            starttls:
              enable: true


  # Utilisation des cookies pour la gestion des sessions
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  servlet:
    session:
      cookie:
        name: mySessionCookie
      timeout: 1800




